name: Latest YouTube Videos
on:
  schedule:
    # Runs every hour, on the hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCipSxT7a3rn81vGLw9lqRkg"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          date_format: "mmm d, yyyy" 
          template: "<tr><td><img width=\"140px\" src=\"https://i.ytimg.com/vi/$videoId/mqdefault.jpg\"></td>$newline<td><a href=\"$url\">$title</a><br/>$date</td></tr>$newline" 
          committer_email: "jonah@freshidea.com"
